fix(HMS-3414): Create directories in Containerfile
Commit c854f2f52dc8c4c2455d46bf1416170d69db4b8a broke build process:

```
ERROR: failed to solve: failed to compute cache key: failed to calculate
checksum of ref ji869wphngyfym4bml6014fnn::rdlrmumtn45cgenzunvxem3ds:
"/dist": not found
```

Signed-off-by: Christian Heimes <cheimes@redhat.com>